spark.master                     spark://spark-master:7077
spark.hadoop.fs.defaultFS        hdfs://namenode:9000
spark.hadoop.dfs.client.use.datanode.hostname true
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.session.timeZone       UTC
spark.sql.extensions             io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog
# spark.jars.packages              org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
